const appStrings = {
  "English": {
    "home": "Home",
    "activity": "Activity",
    "settings": "Settings",
    "language": "language",
    "this month's goal": "This month's goal",
    "push-up": "Push-up",
    "sit-up": "Sit-up",
    "reps": "reps",
    "counter": "Counter",
    "stopwatch": "Stopwatch",
    "push":
        "Place your phone on the ground,\nbring your chest close to smartphone to count",
    "sit":
        "Place your phone on the ground,bring your back close to smartphone to count",
    "back to Calendar": "Back to Calendar",
    "change language": "Change language?",
    "cancel": "Cancel",
    "ok": "OK",
    "restart app": "Return to the first screen",
    "infomation": "Infomation",
    "version": "Version",
    "page1 title": "Welcome to Push App!!",
    "page2 title": "You’re Being Watched",
    "page2 body":
        "Show up. Train. Earn your mark. PushApp never forgets — only you decide what it remembers.",
    "page3 title": "About Counting",
    "page3 body":
        "In Count Mode, PushApp automatically counts your repetitions for you. Focus on your push-ups! If some reps aren’t counted, it’s because your push-ups were too shallow — PushApp doesn’t miss a thing.",
    "page4 title": "Ready to Start",
    "page4 body":
        "You’re all set! Start your first session and track your progress. Let’s make every rep count.",
    "explanation": "Explanation",
  },
  "日本語": {
    "home": "Home",
    "activity": "Activity",
    "settings": "Settings",
    "language": "言語",
    "this month's goal": "今月の目標",
    "push-up": "腕立て伏せ",
    "sit-up": "腹筋",
    "reps": "回",
    "counter": "カウンター",
    "stopwatch": "ストップウォッチ",
    "push": "スマホを地面に置いて、\n胸を近づけるとカウントされます",
    "sit": "スマホを地面に置いて、\n背中を近づけるとカウントされます",
    "back to Calendar": "カレンダーに戻る",
    "change language": "言語を変更しますか？",
    "cancel": "キャンセル",
    "ok": "はい",
    "restart app": "最初の画面に戻ります",
    "infomation": "情報",
    "version": "バージョン",
    "page1 title": "Push Appへようこそ!",
    "page2 title": "今日から変わりましょう",
    "page2 body": "さあ、始めましょう。PushAppはあなたの努力を記録し、進捗を見逃しません。あなた次第で、未来が変わります。",
    "page3 title": "カウントについて",
    "page3 body":
        "カウントモードでは、PushAppが自動で回数をカウントしてくれます。腕立て伏せに集中しましょう！カウントされない？ならさらに深くしっかりと行いましょう",
    "page4 title": "準備完了",
    "page4 body": "準備ができました！最初のトレーニングを始めて進捗を記録しましょう。1回1回を大切に。",
    "explanation": "説明",
  },
};
