const appStrings = {
  "English": {
    "home": "Home",
    "activity": "Activity",
    "settings": "Settings",
    "language": "language",
    "this month's goal": "This month's goal",
    "push-up": "Push-up",
    "sit-up": "Sit-up",
    "reps": "reps",
    "counter": "Counter",
    "stopwatch": "Stopwatch",
    "push":
        "Place your phone on the ground,\nbring your chest close to smartphone to count",
    "sit":
        "Place your phone on the ground,\nbring your back close to smartphone to count",
    "back to Calendar": "Back to Calendar",
    "change language": "Change language?",
    "cancel": "Cancel",
    "ok": "OK",
    "restart app": "Return to the first screen",
  },
  "日本語": {
    "home": "Home",
    "activity": "Activity",
    "settings": "Settings",
    "language": "言語",
    "this month's goal": "今月の目標",
    "push-up": "腕立て伏せ",
    "sit-up": "腹筋",
    "reps": "回",
    "counter": "カウンター",
    "stopwatch": "ストップウォッチ",
    "push": "スマホを地面に置いて、\n胸を近づけるとカウントされます",
    "sit": "スマホを地面に置いて、\n背中を近づけるとカウントされます",
    "back to Calendar": "カレンダーに戻る",
    "change language": "言語を変更しますか？",
    "cancel": "キャンセル",
    "ok": "はい",
    "restart app": "最初の画面に戻ります",
  },
};
